### ISSUE TITLE
2.1 Not working; cookie?

### ISSUE THREAD

**Issue by NAL100** [am-silex/anki_cambridge#10]
On the latest version, trying to install the plugin. Getting the following error when I click on Get New Notes from Link:

-----------------------------------
```
Debug info:
Anki 2.1.26 (70784154) Python 3.8.0 Qt 5.13.1 PyQt 5.14.1
Platform: Mac 10.14
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-07-11 23:05:18
Add-ons possibly involved: ⁨Cambridge Dictionary⁩

Error in sys.excepthook:
Traceback (most recent call last):
  File "aqt/errors.py", line 19, in excepthook
  File "aqt/errors.py", line 48, in write
UnicodeEncodeError: 'ascii' codec can't encode character '\u2013' in position 458: ordinal not in range(128)

Original exception was:
Traceback (most recent call last):
  File "/Users/Jim/Library/Application Support/Anki2/addons21/1875288089/main.py", line 20, in ask_user_for_link
    window = LinkDialogue()
  File "/Users/Jim/Library/Application Support/Anki2/addons21/1875288089/gui.py", line 45, in __init__
    self.initUI()
  File "/Users/Jim/Library/Application Support/Anki2/addons21/1875288089/gui.py", line 50, in initUI
      File "aqt/__init__.py", line 185, in fn__
UnicodeEncodeError: 'ascii' codec can't encode character '\u2013' in position 137: ordinal not in range(128)
````

-----------------------------------

Also, I wasn't sure which cookie value exactly to paste into the cookie field from cambridge plus's site. I have like 10 of them, so I tried the JSESSIONID value. Some examples would be helpful.

In the config file it reads:

```
{
    "cookie": "54619xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-x1",
    "wordlist_ids": [
        "209xxxxx"
    ]
}
```

(I added x's as to not reveal the string)

Any help would be great, thanks.

**Comment by am-silex** [comment]
Hi.
I've just checked on the latest version from Anki Add-on site - creating note from link work like magic) Unfortunately, I'm on Windows, maybe that matter
