### ISSUE TITLE
error while adding from from link

### ISSUE THREAD

**Issue by omega3** [am-silex/anki_cambridge#11]
```
Add-ons possibly involved: ⁨Cambridge Dictionary⁩

Caught exception:
Traceback (most recent call last):
  File "/home/user/.local/share/Anki2/addons21/1875288089/gui.py", line 84, in get_word_definitions_from_link
    downloader.get_word_defs()
  File "/home/user/.local/share/Anki2/addons21/1875288089/Cambridge.py", line 85, in get_word_defs
    response = urlopen(req)
  File "urllib/request.py", line 222, in urlopen
  File "urllib/request.py", line 525, in open
  File "urllib/request.py", line 542, in _open
  File "urllib/request.py", line 502, in _call_chain
  File "urllib/request.py", line 1362, in https_open
  File "urllib/request.py", line 1323, in do_open
  File "http/client.py", line 1322, in getresponse
  File "http/client.py", line 303, in begin
  File "http/client.py", line 272, in _read_status
http.client.RemoteDisconnected: Remote end closed connection without response

```

Version 2.1.22 (0ecc189a)
Python 3.8.1 Qt 5.14.1 PyQt 5.14.1

Operating System: Manjaro Linux
KDE Plasma Version: 5.19.3
KDE Frameworks Version: 5.72.0
Qt Version: 5.15.0
Kernel Version: 5.7.9-1-MANJARO
OS Type: 64-bit

I used this link
https://dictionary.cambridge.org/dictionary/english/appointment

By the way, I have a question: have you thought about an add-on that would make use of dictionary on DVD somehow drawing data from its original database files? That would  prevent errors from Cambridge changing their website. Or alternatively from Oxford Advanced Learner's Dictionary on DVD 9th edition.

**Comment by am-silex** [comment]
Hi
Thanks for informing on this issue
It seems that CD change some security policy in request headers and reject "malformed" headers - I'll fix it ASAP 

PS: No, I've not considered parsing anything from DVDs as it's 21st century and now everything is in the cloud

**Comment by omega3** [comment]
```
Caught exception:
Traceback (most recent call last):
  File "/home/user/.local/share/Anki2/addons21/1875288089/gui.py", line 84, in get_word_definitions_from_link
    downloader.get_word_defs()
  File "/home/user/.local/share/Anki2/addons21/1875288089/Cambridge.py", line 85, in get_word_defs
    response = urlopen(req)
  File "urllib/request.py", line 222, in urlopen
  File "urllib/request.py", line 525, in open
  File "urllib/request.py", line 542, in _open
  File "urllib/request.py", line 502, in _call_chain
  File "urllib/request.py", line 1362, in https_open
  File "urllib/request.py", line 1323, in do_open
  File "http/client.py", line 1322, in getresponse
  File "http/client.py", line 303, in begin
  File "http/client.py", line 272, in _read_status
http.client.RemoteDisconnected: Remote end closed connection without response
```

**Comment by am-silex** [comment]
Culprit is found - 2 missing headers
- User-Agent
- Host
Added. Now addon works as before
