### ISSUE TITLE
Fetching failed

### ISSUE THREAD

**Issue by allenypan** [am-silex/anki_cambridge#15]
Fetching failed：
Traceback (most recent call last):
  File "C:\Users\allen\AppData\Roaming\Anki2\addons21\1875288089\gui.py", line 538, in run
    self._fetch_wordlist()
  File "C:\Users\allen\AppData\Roaming\Anki2\addons21\1875288089\gui.py", line 568, in _fetch_wordlist
    self.downloader.fetch_wordlist_entries(wordlist_id)
  File "C:\Users\allen\AppData\Roaming\Anki2\addons21\1875288089\Cambridge.py", line 323, in fetch_wordlist_entries
    response = urlopen(self.req)
  File "urllib\request.py", line 222, in urlopen
  File "urllib\request.py", line 525, in open
  File "urllib\request.py", line 542, in _open
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 1393, in https_open
  File "urllib\request.py", line 1350, in do_open
  File "http\client.py", line 1255, in request
  File "http\client.py", line 1296, in _send_request
  File "http\client.py", line 1228, in putheader
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2026' in position 512: ordinal not in range(256)

**Comment by BPylypenko** [comment]
Most possibly, in my case, you have a `...` (three dots) symbol in your cookies.
 After that, I tried to get my cookies through the browser in the console: `document.cookie`. 
**document.URL**: `'https://dictionary.cambridge.org/dictionary/english/'`

But It didn't work either.
It just said that:
> Fetching failed:
Authentification failed. Either your cookie expired or your are trying to delete entries from a community wordlist.

But my wordlist is not public and I had only copied cookies, so it's impossible that they expired.

@am-silex, please, could you show a step-by-step guide on how to authenticate to the Cambridge dictionary?

**Comment by am-silex** [comment]
As I wrote in Readme this authenticating method has been used provisionally. Unfortunately, no one has come forward so far with contribution to implement 'proper' mechanism - a form with username & pass.

**Comment by am-silex** [comment]
Not related to Add-On issue.
