### ISSUE TITLE
Fetching failed:

### ISSUE THREAD

**Issue by Mattwang12** [am-silex/anki_cambridge#22]
When I Fetch new words from user wordlists but always fail, it shows as below, could you help me how to fix it? Thank you a lot.  👍

Fetching failed:
Traceback (most recent call last):
  File "C:\Users\MATT\AppData\Roaming\Anki2\addons21\1875288089\gui.py", line 538, in run
    self._fetch_wordlist()
  File "C:\Users\MATT\AppData\Roaming\Anki2\addons21\1875288089\gui.py", line 568, in _fetch_wordlist
    self.downloader.fetch_wordlist_entries(wordlist_id)
  File "C:\Users\MATT\AppData\Roaming\Anki2\addons21\1875288089\Cambridge.py", line 323, in fetch_wordlist_entries
    response = urlopen(self.req)
  File "urllib.request", line 214, in urlopen
  File "urllib.request", line 523, in open
  File "urllib.request", line 632, in http_response
  File "urllib.request", line 561, in error
  File "urllib.request", line 494, in _call_chain
  File "urllib.request", line 641, in http_error_default
urllib.error.HTTPError: HTTP Error 400: Bad Request

**Comment by am-silex** [comment]
Seems not related to Add-On itself - may be authorization, connectivity or service issue.
