### ISSUE TITLE
Add-on compatibility with Anki Qt6

### ISSUE THREAD

**Issue by haim** [am-silex/anki_cambridge#29]
Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 6.5.3 PyQt 6.5.3
Platform: macOS-14.2.1-x86_64-i386-64bit
Anki message :
The following add-ons failed to load: ⁨
[Cambridge Dictionary](https://ankiweb.net/shared/info/1875288089)⁩
They may need to be updated to support this version of Anki. Click the Check for Updates button to see if any updates are available.
You can use the Copy Debug Info button to get information that you can paste in a report to the add-on author.
For add-ons that don't have an update available, you can disable or delete the add-on to prevent this message from appearing.

Debug info:

When loading Cambridge Dictionary:
Traceback (most recent call last):
  File "aqt.addons", line 245, in loadAddons
  File "/Users/den/Library/Application Support/Anki2/addons21/1875288089/__init__.py", line 19, in <module>
    from . import main
  File "/Users/den/Library/Application Support/Anki2/addons21/1875288089/main.py", line 12, in <module>
    from .gui import *
  File "/Users/den/Library/Application Support/Anki2/addons21/1875288089/gui.py", line 15, in <module>
    from PyQt5.QtGui import QIcon, QFont
ModuleNotFoundError: No module named 'PyQt5'

**Comment by am-silex** [comment]
https://docs.ankiweb.net/platform/windows/installing.html#qt5-vs-qt6
I'll see what could be done.

**Comment by Roblexander** [comment]
Same issue, I guess. For what it's worth:

Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 6.6.1 PyQt 6.6.1
Platform: Windows-10-10.0.19045

When loading Cambridge Dictionary:
Traceback (most recent call last):
  File "aqt.addons", line 245, in loadAddons
  File "C:\Users\Robert\AppData\Roaming\Anki2\addons21\1875288089\__init__.py", line 19, in <module>
    from . import main
  File "C:\Users\Robert\AppData\Roaming\Anki2\addons21\1875288089\main.py", line 12, in <module>
    from .gui import *
  File "C:\Users\Robert\AppData\Roaming\Anki2\addons21\1875288089\gui.py", line 15, in <module>
    from PyQt5.QtGui import QIcon, QFont
ModuleNotFoundError: No module named 'PyQt5'
